/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/icon/': RouteRecordInfo<'/icon/', '/icon', Record<never, never>, Record<never, never>>,
    '/platform/[...path]': RouteRecordInfo<'/platform/[...path]', '/platform/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/platform/farmework/icon/': RouteRecordInfo<'/platform/farmework/icon/', '/platform/farmework/icon', Record<never, never>, Record<never, never>>,
    '/portal1': RouteRecordInfo<'/portal1', '/platform/portal', Record<never, never>, Record<never, never>>,
    '/test/': RouteRecordInfo<'/test/', '/test', Record<never, never>, Record<never, never>>,
  }
}
